server:
  #port: ${random.int[10000,19999]}
  port: 1000
zhou:
  tcpHostIp: 127.0.0.1
  tcpHostPort: 99
  isTcpSever: true
#springBoot2.0 以上配置日志 root  
logging:
  level:
    root: debug,info,error  
  