package com.version.common.event;

import java.io.Serializable;

public enum NetEventType implements Serializable {
	SESSION_CREATED("SESSION_CREATED"), SESSION_OPENED("SESSION_OPENED"), SESSION_CLOSED("SESSION_CLOSED"),
	SESSION_EXCEPTION("SESSION_EXCEPTION"), FRAME_BEFORE_CREATE_ROOM("FRAME_BEFORE_CREATE_ROOM"),
	FRAME_BEFORE_JOIN_ROOM("FRAME_BEFORE_JOIN_ROOM"), FRAME_DISSOLUTION_ROOM("FRAME_DISSOLUTION_ROOM"),
	FRAME_GOLD_FORCE_EXIT_ROOM("FRAME_GOLD_FORCE_EXIT_ROOM"), FRAME_HEARTBEAT_EVENT("FRAME_HEARTBEAT_EVENT"),
	FRAME_REMOVE_OFFLINE_CONTROLLER("FRAME_REMOVE_OFFLINE_CONTROLLER"), FRAME_ROOM_BEGIN("FRAME_ROOM_BEGIN"),
	FRAME_SOMEONE_CREATE_ROOM("FRAME_SOMEONE_CREATE_ROOM"), FRAME_SOMEONE_EXIT_ROOM("FRAME_SOMEONE_EXIT_ROOM"),
	FRAME_SOMEONE_JOIN_ROOM("FRAME_SOMEONE_JOIN_ROOM"), FRAME_SOMEONE_LOGIN_SUCESS("FRAME_SOMEONE_LOGIN_SUCESS"),
	FRAME_SOMEONE_LOGINOUT("FRAME_SOMEONE_LOGINOUT"), FRAME_CREATE_ROBOT_MIRROR("FRAME_CREATE_ROBOT_MIRROR"),
	FRAME_GET_CURRENT_HEALTH("FRAME_GET_CURRENT_HEALTH"), FRAME_SOMEONE_REQ_GAMEREADY("FRAME_SOMEONE_REQ_GAMEREADY"),
	FRAME_SOMEONE_AGREE_DISSOLUTION_CARD_ROOM("FRAME_SOMEONE_AGREE_DISSOLUTION_CARD_ROOM"),
	FRAME_SOMEONE_REQ_DISSOLUTION_CARD_ROOM("FRAME_SOMEONE_REQ_DISSOLUTION_CARD_ROOM"),
	FRAME_SOMEONE_ADD_WATCHER_LIST("FRAME_SOMEONE_ADD_WATCHER_LIST"),
	FRAME_SOMEONE_REMOVE_WATCHER_LIST("FRAME_SOMEONE_REMOVE_WATCHER_LIST"),
	FRAME_CAN_REMOVE_WATCHER_FROM_ROOM("FRAME_CAN_REMOVE_WATCHER_FROM_ROOM"),
	FRAME_RECONNECT_JOIN_ROOM_SUCCESS("FRAME_RECONNECT_JOIN_ROOM_SUCCESS"),
	FRAME_GATE_GET_PLAT_PLAYER_BY_ID("FRAME_GATE_GET_PLAT_PLAYER_BY_ID"),
	GAME_RECONNECT_JOIN_ROOM_SUCCESS("GAME_RECONNECT_JOIN_ROOM_SUCCESS"),
	GAME_BEFORE_CREATE_ROOM("GAME_BEFORE_CREATE_ROOM"), GAME_BEFORE_JOIN_ROOM("GAME_BEFORE_JOIN_ROOM"),
	GAME_BEFORE_DISSOLUTION_ROOM("GAME_BEFORE_DISSOLUTION_ROOM"),
	GAME_GOLD_FORCE_EXIT_ROOM("GAME_GOLD_FORCE_EXIT_ROOM"), GAME_HEARBEAT_CHECK("GAME_HEARBEAT_CHECK"),
	GAME_REMOVE_OFFLINE_CONTROLLER("GAME_REMOVE_OFFLINE_CONTROLLER"), GAME_ROOM_BEGIN("GAME_ROOM_BEGIN"),
	GAME_SOMEONE_CREATE_ROOM("GAME_SOMEONE_CREATE_ROOM"), GAME_SOMEONE_EXIT_ROOM("GAME_SOMEONE_EXIT_ROOM"),
	GAME_SOMEONE_JOIN_ROOM("GAME_SOMEONE_JOIN_ROOM"), GAME_SOMEONE_LOGIN_SUCCESS("GAME_SOMEONE_LOGIN_SUCCESS"),
	GAME_SOMEONE_LOGINOUT("GAME_SOMEONE_LOGINOUT"), GAME_GET_CURRENT_HEALTH("GAME_GET_CURRENT_HEALTH"),
	GAME_SOMEONE_REQ_GAMEREADY("GAME_SOMEONE_REQ_GAMEREADY"),
	GAME_SOMEONE_AGREE_DISSOLUTION_CARD_ROOM("GAME_SOMEONE_AGREE_DISSOLUTION_CARD_ROOM"),
	GAME_SOMEONE_REQ_DISSOLUTION_CARD_ROOM("GAME_SOMEONE_REQ_DISSOLUTION_CARD_ROOM"),
	GAME_SOMEONE_ADD_WATCHER_LIST("GAME_SOMEONE_ADD_WATCHER_LIST"),
	GAME_SOMEONE_REMOVE_WATCHER_LIST("GAME_SOMEONE_REMOVE_WATCHER_LIST"),
	GAME_CAN_REMOVE_WATCHER_FROM_ROOM("GAME_CAN_REMOVE_WATCHER_FROM_ROOM"), GAME_ROOM_EXT_INFO("GAME_BEFORE_JOIN_ROOM"),
	FRAME_NOTIFY_MATCH_START("FRAME_NOTIFY_MATCH_START"), GAME_NOTIFY_MATCH_START("GAME_NOTIFY_MATCH_START"),
	FRAME_NOTIFY_MATCH_OVER("FRAME_NOTIFY_MATCH_OVER"), GAME_NOTIFY_MATCH_OVER("GAME_NOTIFY_MATCH_OVER"),
	FRAME_NOTIFY_MATCH_ROOM_START("FRAME_NOTIFY_MATCH_ROOM_START"),
	GAME_NOTIFY_MATCH_ROOM_START("GAME_NOTIFY_MATCH_ROOM_START"), FRAME_CAN_CHANGE_ROOM("FRAME_CAN_CHANGE_ROOM"),
	GAME_CAN_CHANGE_ROOM("GAME_CAN_CHANGE_ROOM");

	private String eventType;

	private NetEventType(String eventType) {
		this.eventType = eventType;
	}

	public String getEventType() {
		return eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

}
