name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Apache Maven Build Automation for Java Project
      uses: NishkarshRaj/Maven_Actions@0.1
      with:
          # Apache Maven hierarchy to be followed in src/main/java/{pkg name} for source code
        src: src/main/java/
