name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build	
      uses: qcastel/github-actions-maven/actions/maven@master
      with:
        maven-args: "clean install"
