name: Java CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:  
       servers: '[{ "id": "docker-aliyun", "username": "2902348036@qq.com", "password": "742042932mn" ,"configuration": {"email": "2902348036@qq.com"}}]'   
    - name: Build with Maven  
      run: mvn -B package  --file pom.xml --settings= /home/runner/.m2/settings.xml
      
    
      
